// TEMPORARY parity reference — deleted in Task 5. Exact copy of tool-schemas.ts TOOLS pre-refactor.
import type { ToolSchema } from './types';

const str = { type: 'string' } as const;

export const TOOLS_LEGACY: ToolSchema[] = [
  { type: 'function', function: { name: 'get_portfolio', description: "Use when the user asks about their balances, holdings, net worth, or overall portfolio value. Returns the user's USDC + ETH balances, farming position, and total USD value.", parameters: { type: 'object', properties: {}, additionalProperties: false } } },
  { type: 'function', function: { name: 'get_payment_history', description: "Use when the user asks about past or recent payments, receipts, or what they've paid. Returns their recent paid orders.", parameters: { type: 'object', properties: { limit: { type: 'number' } }, additionalProperties: false } } },
  { type: 'function', function: { name: 'get_farming_summary', description: "Use when the user asks about their farming position, yield, or earnings. Returns their Compound farming principal, current value, and earnings.", parameters: { type: 'object', properties: {}, additionalProperties: false } } },
  { type: 'function', function: { name: 'get_spending_analytics', description: 'Use when the user asks how much they have spent or wants spending trends over time. Returns a chart-ready series bucketed by day/week/month.', parameters: { type: 'object', properties: { period: { type: 'string', enum: ['day', 'week', 'month'] } }, additionalProperties: false } } },
  { type: 'function', function: { name: 'resolve_recipient', description: 'Use to look up who a @username or 0x address belongs to WITHOUT sending money (e.g. "who is @bob"). To actually send, call build_transfer directly — it resolves the handle itself. Do NOT use this if the user gave a full 0x address you can pass straight through.', parameters: { type: 'object', properties: { recipient: str }, required: ['recipient'], additionalProperties: false } } },
  { type: 'function', function: { name: 'build_transfer', description: 'Use when the user wants to send or pay USDC/ETH to someone. Builds a proposal the user reviews and signs in-app; it NEVER moves funds. Call this DIRECTLY with the recipient the user named — pass a @username as-is (the backend resolves it); do NOT ask for a 0x address. Only call this once you have BOTH a recipient AND an explicit amount from the user: if the amount is missing or vague ("some", "a bit"), ask the user how much first — never assume or default an amount. amountBase is base units of the chosen asset: USDC has 6 decimals (1 USDC = 1000000); ETH is wei (1 ETH = 1000000000000000000). Default asset is USDC (gasless).', parameters: { type: 'object', properties: { recipient: { type: 'string', description: 'A @username or a 0x wallet address; pass the @username as-is.' }, amountBase: { type: 'string', description: 'Amount in base units of the asset (USDC 6-decimals, or ETH wei). Must come from the user — never guessed.' }, asset: { type: 'string', enum: ['USDC', 'ETH'], description: 'Which asset to send. Defaults to USDC.' } }, required: ['recipient', 'amountBase'], additionalProperties: false } } },
  { type: 'function', function: { name: 'build_farming_deposit', description: 'Use when the user wants to earn yield / supply / deposit USDC into farming. Builds a proposal the user signs in-app; it never executes. Requires an explicit amount from the user — if none was given, ask how much first. amountBase = 6-decimal USDC base units.', parameters: { type: 'object', properties: { amountBase: str }, required: ['amountBase'], additionalProperties: false } } },
  { type: 'function', function: { name: 'build_farming_withdraw', description: 'Use when the user wants to take USDC out of farming. Builds a proposal the user signs in-app; it never executes. amount = 6-decimal base units, or the literal "all" to withdraw everything. If the user gave no amount, ask how much (or whether they mean all).', parameters: { type: 'object', properties: { amount: str }, required: ['amount'], additionalProperties: false } } },
  { type: 'function', function: { name: 'get_token_info', description: 'Use to answer any question about a specific cryptocurrency\'s price or market ("how much is BTC", "tell me about solana"). Accepts a name or symbol (e.g. "BTC", "bitcoin", "solana"). Returns price, 24h/7d/30d change, market cap, rank, supply, ATH, and a short description. Summarize and analyze the result for the user — do not dump raw numbers.', parameters: { type: 'object', properties: { query: { type: 'string', description: 'Token name or symbol, e.g. "BTC" or "solana".' } }, required: ['query'], additionalProperties: false } } },
  { type: 'function', function: { name: 'get_top_coins', description: 'Use for "top coins", "biggest cryptocurrencies", or "what is trending" questions. Lists the top cryptocurrencies by market capitalization (default 10).', parameters: { type: 'object', properties: { limit: { type: 'number' } }, additionalProperties: false } } },
];
