-- AlterTable
ALTER TABLE "Transfer" ADD COLUMN     "asset" TEXT NOT NULL DEFAULT 'USDC',
ALTER COLUMN "nonce" DROP NOT NULL,
ALTER COLUMN "digest" DROP NOT NULL,
ALTER COLUMN "validBefore" DROP NOT NULL;
